# -*- coding: utf-8 -*-
"""Dữ liệu dùng chung của website: thông tin pháp nhân, menu, lĩnh vực dịch vụ, bài viết.

Nội dung lĩnh vực dịch vụ được chuyển từ website cũ (willmichco/Website).
Sửa nội dung tại đây rồi chạy:  python3 tools/build.py
"""

# ---------------------------------------------------------------------------
# Cấu hình tên miền. Khi có tên miền riêng: đổi SITE_URL thành https://tenmien.vn
# và BASE_PATH thành "/".
# ---------------------------------------------------------------------------
SITE_URL = "https://luat-su-nam-phap-ly.willmich-co.chatgpt.site"
BASE_PATH = "/"

FIRM = {
    "legal_name": "Công Ty Luật TNHH Luật Sư Nam",
    "short_name": "Luật Sư Nam",
    "brand": "LSN Law Firm",
    "slogan": "Kiến tạo công lý bền vững",
    "phone": "0983 498 499",
    "phone_tel": "0983498499",
    "phone_intl": "+84983498499",
    "email": "luatsunam.hcm@gmail.com",
    "zalo": "https://zalo.me/0983498499",
    "street": "22c Vũ Ngọc Phan",
    "ward": "Phường Bình Lợi Trung",
    "city": "Thành phố Hồ Chí Minh",
    "hours": "Thứ 2 – Thứ 6: 08:00 – 17:30",
    "hours_note": "Ngoài giờ và cuối tuần: tiếp nhận theo lịch hẹn trước",
    "maps_query": "22c%20V%C5%A9%20Ng%E1%BB%8Dc%20Phan%2C%20Ph%C6%B0%E1%BB%9Dng%20B%C3%ACnh%20L%E1%BB%A3i%20Trung%2C%20Th%C3%A0nh%20ph%E1%BB%91%20H%E1%BB%93%20Ch%C3%AD%20Minh",
}
FIRM["address"] = f'{FIRM["street"]}, {FIRM["ward"]}, {FIRM["city"]}'

# ---------------------------------------------------------------------------
# Lĩnh vực dịch vụ
# ---------------------------------------------------------------------------
SERVICES = [
    {
        "slug": "thua-ke",
        "name": "Thừa kế",
        "icon": "i-inherit",
        "short": "Tư vấn lập di chúc, phân chia di sản, khai nhận thừa kế và giải quyết tranh chấp giữa các bên liên quan.",
        "title": "Luật sư tư vấn Thừa kế tại TP.HCM",
        "description": "Luật sư tư vấn lập di chúc, khai nhận và phân chia di sản thừa kế, giải quyết tranh chấp thừa kế theo Bộ luật Dân sự. Liên hệ 0983 498 499.",
        "eyebrow": "Dịch vụ pháp lý cá nhân",
        "lead": "Tư vấn toàn diện từ lập di chúc, xác định di sản và người thừa kế đến khai nhận, phân chia tài sản và giải quyết tranh chấp tại Tòa án.",
        "image_alt": "Luật sư trao đổi hồ sơ thừa kế với khách hàng tại văn phòng",
        "focus_title": "Đúng quyền, đúng tài sản, đúng thủ tục",
        "focus_text": "Kiểm tra hiệu lực di chúc, phạm vi di sản, hàng thừa kế, thời hiệu và nghĩa vụ tài sản trước khi đề xuất phương án.",
        "tags": ["Di chúc", "Khai nhận di sản", "Phân chia", "Tranh chấp"],
        "scope_title": "Giải pháp thừa kế theo từng hoàn cảnh gia đình",
        "scope_intro": "Mỗi hồ sơ thừa kế có thể liên quan đồng thời đến quan hệ nhân thân, tài sản chung, nhà đất, khoản nợ và ý chí của người để lại di sản. Luật Sư Nam rà soát tổng thể trước khi tư vấn để khách hàng hiểu rõ quyền, nghĩa vụ và lựa chọn phù hợp.",
        "scope": [
            ("Lập và rà soát di chúc", "Tư vấn hình thức, nội dung, người làm chứng, người quản lý di sản và điều kiện có hiệu lực; nhận diện các nội dung có nguy cơ bị vô hiệu."),
            ("Xác định di sản, người thừa kế", "Phân định tài sản riêng, phần tài sản trong khối tài sản chung; xác định hàng thừa kế, người thừa kế không phụ thuộc nội dung di chúc."),
            ("Khai nhận và phân chia di sản", "Hướng dẫn thủ tục khai nhận, thỏa thuận phân chia, từ chối nhận di sản và đăng ký biến động đối với tài sản phải đăng ký."),
            ("Thừa kế nhà đất, cổ phần, tiền gửi", "Rà soát hồ sơ sở hữu, nghĩa vụ tài chính và thủ tục chuyển quyền đối với từng loại tài sản cụ thể."),
            ("Thừa kế có yếu tố nước ngoài", "Tư vấn giấy tờ do nước ngoài cấp, ủy quyền, hợp pháp hóa lãnh sự và thủ tục liên quan đến người thừa kế ở nước ngoài."),
            ("Tranh chấp thừa kế", "Đánh giá chứng cứ, thời hiệu, đề xuất hòa giải hoặc đại diện bảo vệ quyền lợi trong tranh chấp di chúc, di sản và phần thừa kế."),
        ],
        "docs": [
            "Giấy chứng tử và giấy tờ nhân thân của các bên",
            "Di chúc, văn bản tặng cho hoặc thỏa thuận đã có",
            "Giấy chứng nhận nhà đất, giấy tờ tài sản, sao kê",
            "Tài liệu về khoản nợ và nghĩa vụ của người để lại di sản",
        ],
        "deliverables": [
            "Bản đánh giá quyền thừa kế và rủi ro hồ sơ",
            "Danh mục giấy tờ, thủ tục và lộ trình thực hiện",
            "Dự thảo di chúc, thỏa thuận hoặc văn bản cần thiết",
            "Đại diện làm việc theo phạm vi ủy quyền đã thống nhất",
        ],
        "principle_title": "Nguyên tắc xử lý hồ sơ",
        "principle_text": "Ưu tiên phương án giữ gìn quan hệ gia đình khi còn khả năng thỏa thuận; đồng thời chuẩn bị căn cứ pháp lý và chứng cứ cần thiết để bảo vệ quyền lợi nếu tranh chấp phát sinh.",
        "steps": [
            ("Tiếp nhận thông tin", "Làm rõ người để lại di sản, tài sản và quan hệ gia đình."),
            ("Rà soát pháp lý", "Kiểm tra di chúc, quyền sở hữu, hàng thừa kế và thời hiệu."),
            ("Đề xuất phương án", "So sánh phương án thỏa thuận, công chứng hoặc khởi kiện."),
            ("Hoàn thiện hồ sơ", "Soạn văn bản và hướng dẫn thủ tục theo phương án đã chọn."),
            ("Đại diện và theo dõi", "Làm việc với cơ quan, tổ chức hoặc Tòa án khi được ủy quyền."),
        ],
        "note_title": "Lưu ý",
        "note_text": "Thời hạn và thủ tục cụ thể phụ thuộc loại tài sản, tình trạng giấy tờ và mức độ thống nhất giữa những người thừa kế.",
        "laws": ["Bộ luật Dân sự 2015 (Phần thứ tư – Thừa kế)", "Luật Công chứng 2024", "Luật Đất đai 2024", "Luật Hôn nhân và Gia đình 2014"],
        "cta_eyebrow": "Tư vấn thừa kế",
        "cta_title": "Chuẩn bị đúng từ đầu giúp hạn chế tranh chấp về sau.",
        "cta_text": "Gửi thông tin sơ bộ để luật sư xác định giấy tờ cần thiết và hướng xử lý phù hợp.",
        "related": ["cong-chung", "dat-dai-bat-dong-san", "tranh-tung-giai-quyet-tranh-chap"],
    },
    {
        "slug": "tranh-tung-giai-quyet-tranh-chap",
        "name": "Tranh tụng & Giải quyết tranh chấp",
        "icon": "i-gavel",
        "short": "Đại diện, thương lượng và bảo vệ quyền lợi tại Tòa án, Trọng tài trong tranh chấp thương mại, hợp đồng và lao động.",
        "title": "Luật sư Tranh tụng & Giải quyết tranh chấp",
        "description": "Đại diện, thương lượng, hòa giải và bảo vệ quyền lợi tại Tòa án, Trọng tài trong tranh chấp hợp đồng, thương mại, dân sự và lao động.",
        "eyebrow": "Giải quyết tranh chấp",
        "lead": "Đánh giá hồ sơ, xây dựng chiến lược thương lượng hoặc tố tụng và đại diện bảo vệ quyền, lợi ích hợp pháp của khách hàng trong suốt quá trình giải quyết.",
        "image_alt": "Búa phán quyết trên bàn xét xử",
        "focus_title": "Chiến lược dựa trên chứng cứ",
        "focus_text": "Xác định điểm mạnh, điểm yếu, thời hiệu, nghĩa vụ chứng minh và khả năng thi hành trước khi lựa chọn phương án.",
        "tags": ["Thương lượng", "Tòa án", "Trọng tài", "Thi hành án"],
        "scope_title": "Kiểm soát tranh chấp từ sớm đến khi hoàn tất",
        "scope_intro": "Tranh chấp hiệu quả không chỉ phụ thuộc vào việc khởi kiện. Chúng tôi phân tích mục tiêu thương mại, chi phí, thời gian, khả năng thu hồi và tác động đến quan hệ giữa các bên để thiết kế chiến lược phù hợp.",
        "scope": [
            ("Đánh giá hồ sơ và chứng cứ", "Rà soát hợp đồng, chứng từ, thư từ, thời hiệu, thẩm quyền và nghĩa vụ chứng minh; nhận diện tài liệu còn thiếu."),
            ("Chiến lược trước khởi kiện", "Phân tích yêu cầu, phản biện, biện pháp khẩn cấp tạm thời, chi phí và khả năng thi hành để chọn thời điểm hành động."),
            ("Thương lượng và hòa giải", "Soạn thư yêu cầu, xây dựng kịch bản đàm phán, tham gia hòa giải và rà soát thỏa thuận để bảo đảm khả năng thực hiện."),
            ("Đại diện tại Tòa án", "Chuẩn bị đơn từ, bản trình bày, tài liệu chứng minh; tham gia phiên họp, hòa giải và xét xử theo phạm vi ủy quyền."),
            ("Trọng tài thương mại", "Tư vấn điều khoản trọng tài, thẩm quyền, thời hạn; chuẩn bị hồ sơ và đại diện trong quá trình tố tụng trọng tài."),
            ("Thi hành bản án, quyết định", "Hỗ trợ yêu cầu thi hành án, xác minh điều kiện thi hành, thỏa thuận thi hành và theo dõi việc xử lý tài sản."),
        ],
        "docs": [
            "Hợp đồng, phụ lục, biên bản và chứng từ thanh toán",
            "Email, tin nhắn, thư yêu cầu và phản hồi giữa các bên",
            "Tài liệu giao nhận, nghiệm thu, đối chiếu công nợ",
            "Đơn từ, quyết định hoặc hồ sơ tố tụng đã phát sinh",
        ],
        "deliverables": [
            "Đánh giá sơ bộ về căn cứ, rủi ro và lựa chọn",
            "Chiến lược giải quyết theo từng mốc công việc",
            "Hệ thống văn bản, chứng cứ được chuẩn hóa",
            "Cập nhật tiến độ và khuyến nghị ở mỗi giai đoạn",
        ],
        "principle_title": "Nguyên tắc chiến lược",
        "principle_text": "Ưu tiên giải pháp đạt mục tiêu thực tế và có khả năng thi hành; tố tụng được lựa chọn khi cần thiết sau khi cân nhắc đầy đủ lợi ích, chi phí và rủi ro.",
        "steps": [
            ("Tiếp nhận hồ sơ", "Xác định bên tranh chấp, yêu cầu và mốc thời gian quan trọng."),
            ("Đánh giá chứng cứ", "Phân tích căn cứ, thời hiệu, thẩm quyền và khả năng thi hành."),
            ("Thống nhất chiến lược", "Chọn thương lượng, hòa giải, Tòa án hoặc Trọng tài."),
            ("Triển khai đại diện", "Soạn hồ sơ và tham gia làm việc theo phạm vi ủy quyền."),
            ("Theo dõi kết quả", "Cập nhật tiến độ, điều chỉnh chiến lược và hỗ trợ thi hành."),
        ],
        "note_title": "Lưu ý",
        "note_text": "Không có kết quả tố tụng nào có thể được bảo đảm trước. Đánh giá chỉ chính xác khi luật sư được tiếp cận đầy đủ hồ sơ và chứng cứ liên quan.",
        "laws": ["Bộ luật Tố tụng dân sự 2015 (sửa đổi, bổ sung)", "Bộ luật Dân sự 2015", "Luật Thương mại 2005", "Luật Trọng tài thương mại 2010", "Luật Thi hành án dân sự"],
        "cta_eyebrow": "Đánh giá tranh chấp",
        "cta_title": "Chuẩn bị hồ sơ sớm giúp bảo toàn chứng cứ và lợi thế.",
        "cta_text": "Gửi tài liệu ban đầu để luật sư xác định thời hạn và hướng xử lý cần ưu tiên.",
        "related": ["dan-su", "lao-dong-viec-lam", "dat-dai-bat-dong-san"],
    },
    {
        "slug": "hon-nhan-gia-dinh",
        "name": "Hôn nhân & Gia đình",
        "icon": "i-heart",
        "short": "Tư vấn ly hôn, quyền nuôi con, cấp dưỡng, phân chia tài sản chung và các thỏa thuận gia đình một cách kín đáo.",
        "title": "Luật sư Hôn nhân & Gia đình, tư vấn ly hôn",
        "description": "Tư vấn ly hôn thuận tình và đơn phương, quyền nuôi con, cấp dưỡng, phân chia tài sản chung vợ chồng. Thông tin khách hàng được bảo mật theo Luật Luật sư.",
        "eyebrow": "Dịch vụ pháp lý cá nhân",
        "lead": "Tư vấn và đại diện giải quyết ly hôn, quyền nuôi con, cấp dưỡng, tài sản chung, nghĩa vụ chung và các thỏa thuận gia đình với nguyên tắc kín đáo, tôn trọng.",
        "image_alt": "Gia đình cha mẹ và con nhỏ lúc hoàng hôn",
        "focus_title": "Bảo vệ quyền lợi, giảm thiểu xung đột",
        "focus_text": "Đặt quyền lợi hợp pháp của khách hàng và sự ổn định của trẻ em vào trung tâm của phương án xử lý.",
        "tags": ["Ly hôn", "Nuôi con", "Cấp dưỡng", "Tài sản"],
        "scope_title": "Giải quyết rõ ràng những vấn đề quan trọng của gia đình",
        "scope_intro": "Luật Sư Nam giúp khách hàng nhìn rõ quyền, nghĩa vụ và hệ quả của từng lựa chọn. Hồ sơ được xử lý trên cơ sở bảo mật thông tin, tôn trọng hoàn cảnh riêng và ưu tiên giải pháp có thể thực hiện lâu dài.",
        "scope": [
            ("Ly hôn thuận tình", "Tư vấn điều kiện, chuẩn bị hồ sơ và hoàn thiện thỏa thuận về con, tài sản, nghĩa vụ chung để thực hiện thủ tục tại Tòa án."),
            ("Ly hôn đơn phương", "Đánh giá căn cứ, thẩm quyền, chứng cứ; soạn đơn và đại diện giải quyết khi một bên không đồng thuận hoặc vắng mặt."),
            ("Quyền nuôi con và cấp dưỡng", "Phân tích điều kiện chăm sóc, nguyện vọng của con, mức cấp dưỡng và tài liệu cần thiết để bảo vệ lợi ích của trẻ."),
            ("Tài sản và nghĩa vụ chung", "Xác định tài sản chung, riêng, công sức đóng góp, khoản nợ và phương án phân chia nhà đất, tiền, cổ phần hoặc tài sản kinh doanh."),
            ("Hôn nhân có yếu tố nước ngoài", "Hướng dẫn hồ sơ, ủy quyền, giấy tờ nước ngoài và thủ tục đối với người đang cư trú hoặc có tài sản ở nước ngoài."),
            ("Thỏa thuận gia đình", "Soạn và rà soát thỏa thuận về chế độ tài sản, phân chia tài sản trong thời kỳ hôn nhân, nuôi con và các cam kết liên quan."),
        ],
        "docs": [
            "Giấy chứng nhận kết hôn và giấy tờ nhân thân",
            "Giấy khai sinh của con và tài liệu về việc chăm sóc",
            "Giấy tờ nhà đất, tài khoản, cổ phần và tài sản khác",
            "Chứng từ về thu nhập, khoản nợ và nghĩa vụ chung",
        ],
        "deliverables": [
            "Đánh giá quyền lợi và các điểm cần ưu tiên",
            "Phương án về con, tài sản và nghĩa vụ tài chính",
            "Hồ sơ, đơn từ và thỏa thuận được chuẩn hóa",
            "Đại diện làm việc theo phạm vi đã thống nhất",
        ],
        "principle_title": "Nguyên tắc bảo mật và nhân văn",
        "principle_text": "Thông tin gia đình được tiếp nhận thận trọng. Chúng tôi khuyến khích thỏa thuận khi phù hợp, nhưng luôn chuẩn bị phương án pháp lý đầy đủ để bảo vệ khách hàng và trẻ em.",
        "steps": [
            ("Trao đổi riêng tư", "Xác định mong muốn, tình trạng hôn nhân, con và tài sản."),
            ("Rà soát hồ sơ", "Phân loại vấn đề đã thống nhất và còn tranh chấp."),
            ("Đề xuất phương án", "Phân tích lựa chọn thỏa thuận hoặc yêu cầu Tòa án."),
            ("Hoàn thiện thủ tục", "Soạn hồ sơ, nộp và theo dõi quá trình giải quyết."),
            ("Đồng hành sau quyết định", "Hướng dẫn thi hành và xử lý vấn đề phát sinh."),
        ],
        "note_title": "Lưu ý",
        "note_text": "Thời gian giải quyết phụ thuộc mức độ thống nhất, nơi cư trú của các bên, tình trạng tài sản và lịch làm việc của cơ quan có thẩm quyền.",
        "laws": ["Luật Hôn nhân và Gia đình 2014", "Bộ luật Tố tụng dân sự 2015 (sửa đổi, bổ sung)", "Bộ luật Dân sự 2015"],
        "cta_eyebrow": "Tư vấn kín đáo",
        "cta_title": "Một phương án rõ ràng giúp gia đình giảm thêm áp lực.",
        "cta_text": "Trao đổi riêng với luật sư để xác định quyền lợi và các bước cần thực hiện.",
        "related": ["thua-ke", "cong-chung", "dan-su"],
    },
    {
        "slug": "dat-dai-bat-dong-san",
        "name": "Đất đai & Bất động sản",
        "icon": "i-house",
        "short": "Rà soát pháp lý dự án, giao dịch, cấp giấy chứng nhận và giải quyết tranh chấp đất đai, nhà ở.",
        "title": "Luật sư Đất đai & Bất động sản",
        "description": "Rà soát pháp lý dự án và giao dịch bất động sản, thủ tục cấp Giấy chứng nhận, giải quyết tranh chấp đất đai, nhà ở theo Luật Đất đai hiện hành.",
        "eyebrow": "Dịch vụ pháp lý tài sản",
        "lead": "Rà soát pháp lý giao dịch, hồ sơ nhà đất, dự án và đại diện giải quyết thủ tục, khiếu nại, tranh chấp liên quan đến quyền sử dụng đất, nhà ở.",
        "image_alt": "Ngôi nhà và khuôn viên sân vườn",
        "focus_title": "Kiểm soát rủi ro trước giao dịch",
        "focus_text": "Làm rõ quyền sở hữu, quy hoạch, hạn chế giao dịch, nghĩa vụ tài chính và khả năng thực hiện thủ tục trước khi ký kết.",
        "tags": ["Nhà đất", "Giao dịch", "Dự án", "Tranh chấp"],
        "scope_title": "Pháp lý rõ ràng cho tài sản có giá trị lớn",
        "scope_intro": "Nhà đất thường gắn với hồ sơ qua nhiều thời kỳ và nhiều chủ thể. Chúng tôi kiểm tra nguồn gốc, hiện trạng pháp lý, quy hoạch, giao dịch bảo đảm và điều kiện chuyển quyền trước khi đề xuất lộ trình.",
        "scope": [
            ("Rà soát trước giao dịch", "Kiểm tra giấy chứng nhận, chủ thể, quy hoạch, thế chấp, hạn chế chuyển nhượng, điều kiện bán và các điều khoản đặt cọc."),
            ("Thủ tục nhà đất", "Hỗ trợ cấp, cấp đổi giấy chứng nhận; sang tên, tặng cho, thừa kế, hợp thửa, tách thửa và đăng ký biến động."),
            ("Hợp đồng và đặt cọc", "Soạn, rà soát hợp đồng đặt cọc, chuyển nhượng, thuê, hợp tác; thiết kế điều kiện thanh toán và cơ chế xử lý vi phạm."),
            ("Tranh chấp quyền sử dụng đất", "Tư vấn tranh chấp ranh giới, lối đi, quyền sử dụng, giao dịch vô hiệu và yêu cầu hủy, chỉnh lý giấy chứng nhận."),
            ("Thu hồi, bồi thường, tái định cư", "Rà soát phương án bồi thường, hỗ trợ, tái định cư; tư vấn khiếu nại và đại diện làm việc theo quy định."),
            ("Pháp lý dự án bất động sản", "Rà soát chủ trương, đất đai, xây dựng, điều kiện kinh doanh, huy động vốn, mua bán và chuyển nhượng dự án."),
        ],
        "docs": [
            "Giấy chứng nhận và hồ sơ kỹ thuật thửa đất, căn nhà",
            "Hợp đồng, đặt cọc, giấy giao nhận tiền và biên bản",
            "Thông tin quy hoạch, thế chấp hoặc thông báo của cơ quan",
            "Đơn từ, quyết định và tài liệu tranh chấp đã có",
        ],
        "deliverables": [
            "Báo cáo tình trạng pháp lý và rủi ro trọng yếu",
            "Danh mục điều kiện cần hoàn thiện trước giao dịch",
            "Hợp đồng, văn bản và hồ sơ thủ tục phù hợp",
            "Phương án thương lượng, khiếu nại hoặc tố tụng",
        ],
        "principle_title": "Nguyên tắc thẩm tra",
        "principle_text": "Không chỉ dựa trên bản sao giấy chứng nhận. Việc đánh giá được thực hiện cùng các tài liệu về chủ thể, hiện trạng, quy hoạch, giao dịch bảo đảm và lịch sử chuyển quyền mà khách hàng cung cấp hoặc có thể xác minh.",
        "steps": [
            ("Xác định mục tiêu", "Làm rõ giao dịch, thủ tục hoặc tranh chấp cần xử lý."),
            ("Kiểm tra hồ sơ", "Rà soát quyền sở hữu, quy hoạch và hạn chế pháp lý."),
            ("Đánh giá rủi ro", "Phân loại vấn đề cần khắc phục và điều kiện tiên quyết."),
            ("Triển khai phương án", "Soạn hồ sơ, đàm phán hoặc làm việc với cơ quan."),
            ("Hoàn tất và hậu kiểm", "Theo dõi đăng ký, bàn giao và nghĩa vụ sau giao dịch."),
        ],
        "note_title": "Lưu ý",
        "note_text": "Kết luận pháp lý phụ thuộc tài liệu thực tế và thông tin từ cơ quan có thẩm quyền. Không nên đặt cọc hoặc thanh toán lớn khi tình trạng hồ sơ chưa được làm rõ.",
        "laws": ["Luật Đất đai 2024", "Luật Nhà ở 2023", "Luật Kinh doanh bất động sản 2023", "Bộ luật Dân sự 2015"],
        "cta_eyebrow": "Rà soát nhà đất",
        "cta_title": "Kiểm tra trước khi ký để giảm rủi ro sau giao dịch.",
        "cta_text": "Gửi hồ sơ hiện có để luật sư xác định các điểm cần xác minh và điều kiện cần bổ sung.",
        "related": ["cong-chung", "thua-ke", "tranh-tung-giai-quyet-tranh-chap"],
    },
    {
        "slug": "lao-dong-viec-lam",
        "name": "Lao động & Việc làm",
        "icon": "i-network",
        "short": "Xây dựng quy chế, hợp đồng lao động, xử lý kỷ luật, chấm dứt hợp đồng và tranh chấp lao động.",
        "title": "Luật sư Lao động & Việc làm",
        "description": "Xây dựng hợp đồng lao động, nội quy, quy chế; tư vấn xử lý kỷ luật, chấm dứt hợp đồng và giải quyết tranh chấp lao động theo Bộ luật Lao động.",
        "eyebrow": "Dịch vụ pháp lý lao động",
        "lead": "Tư vấn thiết lập, quản trị và chấm dứt quan hệ lao động; đại diện giải quyết tranh chấp cho doanh nghiệp và người lao động trên cơ sở đúng quy trình, cân bằng quyền lợi.",
        "image_alt": "Hai doanh nhân bắt tay trong văn phòng",
        "focus_title": "Đúng căn cứ, đúng trình tự, đủ chứng cứ",
        "focus_text": "Kiểm soát rủi ro từ hồ sơ nhân sự và quy trình nội bộ trước khi phát sinh khiếu nại hoặc tranh chấp.",
        "tags": ["Hợp đồng", "Nội quy", "Kỷ luật", "Tranh chấp"],
        "scope_title": "Giải pháp lao động có thể triển khai trong thực tế",
        "scope_intro": "Quan hệ lao động cần cả căn cứ pháp luật và hồ sơ thực hiện nhất quán. Luật Sư Nam rà soát quy trình, chứng cứ và tác động vận hành để đề xuất phương án phù hợp cho từng tình huống.",
        "scope": [
            ("Hợp đồng và hồ sơ nhân sự", "Soạn, rà soát hợp đồng lao động, thử việc, bảo mật, đào tạo, điều chuyển và hồ sơ quản lý người lao động."),
            ("Nội quy và chính sách", "Xây dựng nội quy lao động, quy chế lương thưởng, đánh giá hiệu suất, bảo vệ dữ liệu và quy trình tiếp nhận khiếu nại."),
            ("Kỷ luật lao động", "Đánh giá hành vi, chứng cứ, thời hiệu; hướng dẫn thông báo, họp xử lý và ban hành quyết định đúng trình tự."),
            ("Chấm dứt và tái cơ cấu", "Tư vấn đơn phương chấm dứt, thỏa thuận nghỉ việc, thay đổi cơ cấu, phương án sử dụng lao động và nghĩa vụ thanh toán."),
            ("Tiền lương, bảo hiểm, quyền lợi", "Rà soát tiền lương, làm thêm, phép năm, bảo hiểm, trợ cấp và các khoản bồi thường hoặc hoàn trả liên quan."),
            ("Tranh chấp lao động", "Đại diện thương lượng, hòa giải và tố tụng về kỷ luật, chấm dứt, tiền lương, bảo hiểm, bồi thường và quyền lợi khác."),
        ],
        "docs": [
            "Hợp đồng, phụ lục, mô tả công việc và hồ sơ nhân sự",
            "Nội quy, quy chế, thông báo và biên bản liên quan",
            "Bảng lương, chấm công, bảo hiểm và chứng từ thanh toán",
            "Email, tin nhắn, đánh giá hiệu suất hoặc khiếu nại",
        ],
        "deliverables": [
            "Đánh giá căn cứ và rủi ro của phương án dự kiến",
            "Trình tự công việc và bộ biểu mẫu cần sử dụng",
            "Văn bản nhân sự được soạn hoặc rà soát",
            "Phương án thương lượng và đại diện tranh chấp",
        ],
        "principle_title": "Nguyên tắc phòng ngừa",
        "principle_text": "Hồ sơ lao động được thiết kế để có thể áp dụng nhất quán trong vận hành, đồng thời tạo căn cứ chứng minh nếu cơ quan quản lý hoặc cơ quan giải quyết tranh chấp kiểm tra.",
        "steps": [
            ("Xác định quan hệ lao động", "Làm rõ chủ thể, hợp đồng, vị trí và vấn đề cần xử lý."),
            ("Rà soát quy trình", "Kiểm tra căn cứ, thời hạn, thẩm quyền và chứng cứ."),
            ("Đánh giá lựa chọn", "So sánh phương án nội bộ, thỏa thuận hoặc tranh chấp."),
            ("Chuẩn hóa hồ sơ", "Soạn văn bản và hướng dẫn từng bước thực hiện."),
            ("Theo dõi hậu quả", "Kiểm tra bàn giao, thanh toán và nghĩa vụ sau xử lý."),
        ],
        "note_title": "Lưu ý",
        "note_text": "Kỷ luật hoặc chấm dứt sai căn cứ, sai thời hiệu hay sai thủ tục có thể phát sinh nghĩa vụ nhận lại người lao động, trả lương và bồi thường.",
        "laws": ["Bộ luật Lao động 2019", "Luật Bảo hiểm xã hội 2024", "Bộ luật Tố tụng dân sự 2015 (sửa đổi, bổ sung)"],
        "cta_eyebrow": "Rà soát lao động",
        "cta_title": "Xử lý đúng quy trình ngay từ đầu giúp giảm tranh chấp.",
        "cta_text": "Gửi hồ sơ hiện có để luật sư xác định rủi ro và các bước cần hoàn thiện.",
        "related": ["tranh-tung-giai-quyet-tranh-chap", "dan-su", "hinh-su"],
    },
    {
        "slug": "hinh-su",
        "name": "Hình sự",
        "icon": "i-shield-check",
        "short": "Bào chữa, bảo vệ người bị hại và đồng hành cùng khách hàng trong các giai đoạn điều tra, truy tố, xét xử.",
        "title": "Luật sư bào chữa vụ án Hình sự",
        "description": "Luật sư bào chữa cho người bị buộc tội và bảo vệ quyền lợi bị hại qua các giai đoạn điều tra, truy tố, xét xử, kháng cáo. Hỗ trợ khẩn cấp 0983 498 499.",
        "eyebrow": "Bào chữa & bảo vệ quyền lợi",
        "lead": "Tư vấn khẩn cấp, tham gia bào chữa cho người bị buộc tội và bảo vệ quyền lợi của bị hại, đương sự trong các giai đoạn giải quyết vụ án hình sự.",
        "image_alt": "Tượng nữ thần công lý cầm cán cân",
        "focus_title": "Phản ứng đúng thời điểm, đúng quyền",
        "focus_text": "Hỗ trợ khách hàng hiểu quyền và nghĩa vụ, bảo toàn tài liệu, chuẩn bị phương án làm việc phù hợp với từng giai đoạn tố tụng.",
        "tags": ["Điều tra", "Truy tố", "Xét xử", "Kháng cáo"],
        "scope_title": "Bảo vệ quyền và lợi ích hợp pháp trong tố tụng hình sự",
        "scope_intro": "Vụ án hình sự đòi hỏi xử lý cẩn trọng ngay từ buổi làm việc đầu tiên. Luật Sư Nam nghiên cứu hồ sơ, đối chiếu chứng cứ, theo dõi thủ tục và xây dựng luận điểm bào chữa hoặc bảo vệ trên cơ sở pháp luật và tài liệu khách quan.",
        "scope": [
            ("Tư vấn pháp lý ban đầu", "Giải thích quyền, nghĩa vụ, trình tự làm việc; hướng dẫn chuẩn bị tài liệu trước khi làm việc với cơ quan tiến hành tố tụng."),
            ("Bào chữa cho người bị buộc tội", "Tham gia từ giai đoạn tạm giữ, điều tra, truy tố, xét xử; nghiên cứu hồ sơ và xây dựng luận cứ bào chữa."),
            ("Bảo vệ người bị hại", "Tư vấn tố giác, yêu cầu khởi tố, bồi thường; bảo vệ quyền lợi của bị hại và nguyên đơn dân sự trong vụ án."),
            ("Chứng cứ và kiến nghị tố tụng", "Thu thập, giao nộp, đánh giá tài liệu; đề nghị thực hiện hoạt động tố tụng và khiếu nại quyết định, hành vi khi có căn cứ."),
            ("Kháng cáo và thủ tục sau xét xử", "Đánh giá bản án, tư vấn phạm vi kháng cáo, chuẩn bị đơn và luận cứ; xem xét căn cứ cho thủ tục đặc biệt khi phù hợp."),
            ("Trách nhiệm dân sự trong vụ án", "Tư vấn thiệt hại, hoàn trả, bồi thường, thu giữ tài sản và các quyền lợi dân sự liên quan đến vụ án hình sự."),
        ],
        "docs": [
            "Giấy mời, triệu tập, quyết định hoặc biên bản đã nhận",
            "Tài liệu, dữ liệu, chứng từ liên quan đến sự việc",
            "Thông tin người làm chứng và diễn biến theo thời gian",
            "Tài liệu về nhân thân, khắc phục hậu quả hoặc thiệt hại",
        ],
        "deliverables": [
            "Giải thích rõ quyền, nghĩa vụ và giai đoạn tố tụng",
            "Đánh giá hồ sơ và định hướng làm việc phù hợp",
            "Luận cứ, đơn từ và kiến nghị theo phạm vi dịch vụ",
            "Luật sư tham gia tố tụng khi đủ điều kiện, thủ tục",
        ],
        "principle_title": "Nguyên tắc hành nghề",
        "principle_text": "Bảo mật thông tin, tôn trọng sự thật khách quan, không hướng dẫn khai báo gian dối hoặc cản trở hoạt động tố tụng; mọi luận điểm đều dựa trên chứng cứ và quy định pháp luật.",
        "steps": [
            ("Tiếp nhận khẩn cấp", "Làm rõ giai đoạn, cơ quan thụ lý và mốc làm việc gần nhất."),
            ("Kiểm tra tài liệu", "Rà soát quyết định, biên bản, chứng cứ và thông tin ban đầu."),
            ("Đăng ký tham gia", "Thực hiện thủ tục bào chữa hoặc bảo vệ quyền lợi."),
            ("Nghiên cứu và kiến nghị", "Xây dựng luận điểm, giao nộp tài liệu và đề xuất cần thiết."),
            ("Tham gia tố tụng", "Đồng hành tại buổi làm việc, phiên tòa và giai đoạn sau đó."),
        ],
        "note_title": "Lưu ý quan trọng",
        "note_text": "Không xóa, sửa, che giấu tài liệu hoặc trao đổi nhằm thống nhất lời khai sai sự thật. Hãy cung cấp thông tin trung thực cho luật sư để được tư vấn phù hợp.",
        "laws": ["Bộ luật Hình sự 2015 (sửa đổi, bổ sung 2017, 2025)", "Bộ luật Tố tụng hình sự 2015 (sửa đổi, bổ sung)", "Luật Luật sư 2006 (sửa đổi, bổ sung 2012)"],
        "cta_eyebrow": "Hỗ trợ kịp thời",
        "cta_title": "Vụ việc hình sự cần được đánh giá ngay từ giai đoạn đầu.",
        "cta_text": "Chuẩn bị giấy mời, quyết định và tài liệu hiện có để luật sư xác định việc cần ưu tiên.",
        "related": ["tranh-tung-giai-quyet-tranh-chap", "dan-su", "lao-dong-viec-lam"],
    },
    {
        "slug": "dan-su",
        "name": "Dân sự",
        "icon": "i-scale",
        "short": "Tư vấn hợp đồng, nghĩa vụ, bồi thường, tài sản và đại diện giải quyết tranh chấp dân sự theo đúng trình tự.",
        "title": "Luật sư tư vấn Dân sự",
        "description": "Tư vấn hợp đồng, nghĩa vụ dân sự, bồi thường thiệt hại, quyền tài sản và đại diện giải quyết tranh chấp dân sự đúng trình tự tố tụng.",
        "eyebrow": "Tư vấn & tranh tụng dân sự",
        "lead": "Tư vấn xác lập, thực hiện và bảo vệ quyền dân sự; soạn thảo văn bản, thương lượng và đại diện giải quyết tranh chấp về hợp đồng, tài sản, nghĩa vụ và bồi thường.",
        "image_alt": "Khu cao ốc văn phòng tại thành phố",
        "focus_title": "Làm rõ quyền, nghĩa vụ và chứng cứ",
        "focus_text": "Đánh giá hiệu lực giao dịch, thời hiệu, căn cứ yêu cầu và khả năng thực hiện trước khi lựa chọn thương lượng hoặc tố tụng.",
        "tags": ["Hợp đồng", "Tài sản", "Công nợ", "Bồi thường"],
        "scope_title": "Giải quyết quan hệ dân sự bằng phương án rõ ràng",
        "scope_intro": "Các tranh chấp dân sự thường phát sinh từ thỏa thuận chưa đầy đủ, chứng cứ rời rạc hoặc nghĩa vụ kéo dài. Chúng tôi hệ thống hóa diễn biến, xác định quyền và nghĩa vụ, sau đó đề xuất cách xử lý có tính khả thi.",
        "scope": [
            ("Hợp đồng dân sự", "Soạn, rà soát và xử lý tranh chấp hợp đồng vay, thuê, mua bán, đặt cọc, dịch vụ, hợp tác và các thỏa thuận dân sự khác."),
            ("Vay, nợ và nghĩa vụ thanh toán", "Đánh giá chứng cứ vay, lãi, thời hạn, bảo đảm; soạn yêu cầu thanh toán và đại diện thu hồi khoản nợ hợp pháp."),
            ("Bồi thường thiệt hại", "Xác định hành vi, thiệt hại, quan hệ nhân quả và mức yêu cầu trong các vụ việc thiệt hại về tài sản, sức khỏe, danh dự."),
            ("Quyền sở hữu và tài sản", "Tư vấn xác lập, quản lý, sử dụng, định đoạt tài sản; giải quyết tranh chấp sở hữu chung, đòi tài sản và chiếm hữu."),
            ("Đại diện ngoài tố tụng", "Soạn thư yêu cầu, tham gia thương lượng, hòa giải, làm việc với cá nhân, tổ chức và cơ quan theo phạm vi ủy quyền."),
            ("Tố tụng và thi hành án dân sự", "Chuẩn bị hồ sơ khởi kiện, bảo vệ quyền lợi tại Tòa án và hỗ trợ yêu cầu, theo dõi quá trình thi hành bản án."),
        ],
        "docs": [
            "Hợp đồng, giấy vay, biên nhận và chứng từ thanh toán",
            "Email, tin nhắn, ghi nhận giao nhận hoặc cam kết",
            "Giấy tờ tài sản và tài liệu chứng minh thiệt hại",
            "Đơn từ, biên bản, quyết định đã phát sinh",
        ],
        "deliverables": [
            "Bản đánh giá quyền, nghĩa vụ, thời hiệu và chứng cứ",
            "Phương án thương lượng hoặc tố tụng có lộ trình",
            "Văn bản giao dịch, đơn từ và yêu cầu được chuẩn hóa",
            "Đại diện làm việc và cập nhật tiến độ theo thỏa thuận",
        ],
        "principle_title": "Nguyên tắc xử lý",
        "principle_text": "Giải pháp được xây dựng từ mục tiêu thực tế, giá trị tranh chấp, khả năng chứng minh và khả năng thi hành; tránh kéo dài thủ tục khi có thể đạt thỏa thuận an toàn hơn.",
        "steps": [
            ("Ghi nhận diễn biến", "Hệ thống hóa các bên, giao dịch và mốc thời gian."),
            ("Rà soát chứng cứ", "Xác định hiệu lực, thời hiệu và tài liệu còn thiếu."),
            ("Đề xuất lựa chọn", "So sánh thương lượng, hòa giải và khởi kiện."),
            ("Thực hiện phương án", "Soạn văn bản và đại diện theo phạm vi ủy quyền."),
            ("Theo dõi thi hành", "Hỗ trợ thực hiện thỏa thuận, bản án hoặc quyết định."),
        ],
        "note_title": "Lưu ý",
        "note_text": "Hãy lưu giữ bản gốc, dữ liệu điện tử và chứng từ. Thời hiệu có thể ảnh hưởng trực tiếp đến quyền yêu cầu nên hồ sơ cần được đánh giá sớm.",
        "laws": ["Bộ luật Dân sự 2015", "Bộ luật Tố tụng dân sự 2015 (sửa đổi, bổ sung)", "Luật Thi hành án dân sự"],
        "cta_eyebrow": "Đánh giá vụ việc",
        "cta_title": "Chứng cứ đầy đủ giúp phương án dân sự rõ ràng hơn.",
        "cta_text": "Gửi hợp đồng, chứng từ và diễn biến chính để luật sư đánh giá bước cần ưu tiên.",
        "related": ["tranh-tung-giai-quyet-tranh-chap", "dat-dai-bat-dong-san", "cong-chung"],
    },
    {
        "slug": "cong-chung",
        "name": "Công chứng",
        "icon": "i-doc",
        "short": "Hỗ trợ chuẩn bị hồ sơ, rà soát giao dịch và kết nối công chứng hợp đồng, di chúc, ủy quyền, mua bán, tặng cho.",
        "title": "Hỗ trợ thủ tục Công chứng hợp đồng, di chúc",
        "description": "Hỗ trợ chuẩn bị hồ sơ, rà soát giao dịch và kết nối công chứng hợp đồng mua bán, tặng cho, di chúc, văn bản ủy quyền đúng quy định pháp luật.",
        "eyebrow": "Hỗ trợ hồ sơ & giao dịch",
        "lead": "Rà soát điều kiện giao dịch, chuẩn bị giấy tờ, dự thảo văn bản và phối hợp với tổ chức hành nghề công chứng để khách hàng thực hiện thủ tục thuận lợi, đúng quy định.",
        "image_alt": "Bút ký đặt trên văn bản hợp đồng",
        "focus_title": "Đủ hồ sơ trước khi đặt lịch",
        "focus_text": "Kiểm tra chủ thể, tài sản, nội dung giao dịch và giấy tờ cần thiết nhằm hạn chế việc bổ sung nhiều lần hoặc phát sinh rủi ro.",
        "tags": ["Hợp đồng", "Ủy quyền", "Di chúc", "Nhà đất"],
        "scope_title": "Chuẩn bị giao dịch công chứng rõ ràng và an toàn",
        "scope_intro": "Luật Sư Nam hỗ trợ kiểm tra hồ sơ, giải thích quyền và nghĩa vụ, đề xuất điều khoản và phối hợp đặt lịch. Việc chứng nhận công chứng được thực hiện bởi công chứng viên tại tổ chức hành nghề công chứng có thẩm quyền.",
        "scope": [
            ("Nhà đất và tài sản đăng ký", "Rà soát hồ sơ mua bán, tặng cho, thế chấp, góp vốn, thuê và các giao dịch cần công chứng liên quan đến tài sản."),
            ("Văn bản ủy quyền", "Làm rõ phạm vi, thời hạn, quyền và nghĩa vụ; dự thảo giấy ủy quyền hoặc hợp đồng ủy quyền phù hợp với mục đích sử dụng."),
            ("Di chúc và thừa kế", "Chuẩn bị di chúc, văn bản khai nhận, thỏa thuận phân chia hoặc từ chối nhận di sản cùng giấy tờ nhân thân, tài sản."),
            ("Thỏa thuận tài sản", "Hỗ trợ thỏa thuận tài sản vợ chồng, phân chia tài sản chung, cam kết tài sản riêng và văn bản liên quan."),
            ("Hồ sơ có yếu tố nước ngoài", "Kiểm tra giấy tờ nước ngoài, bản dịch, hợp pháp hóa lãnh sự, ủy quyền và yêu cầu nhận diện chủ thể."),
            ("Rà soát trước khi ký", "Giải thích điều khoản, nghĩa vụ thuế phí, điều kiện bàn giao, thanh toán và rủi ro trước khi khách hàng ký văn bản."),
        ],
        "docs": [
            "Căn cước, hộ chiếu và giấy tờ tình trạng hôn nhân",
            "Giấy tờ chứng minh quyền sở hữu, sử dụng tài sản",
            "Dự thảo, thỏa thuận và giấy tờ giao dịch trước đó",
            "Giấy tờ đại diện, ủy quyền hoặc tài liệu nước ngoài",
        ],
        "docs_title": "Hồ sơ thường cần",
        "deliverables": [
            "Danh mục hồ sơ theo đúng loại giao dịch",
            "Nội dung văn bản được luật sư rà soát trước",
            "Giải thích nghĩa vụ, rủi ro và bước sau công chứng",
            "Hỗ trợ phối hợp lịch với tổ chức công chứng phù hợp",
        ],
        "principle_title": "Phân định rõ vai trò",
        "principle_text": "Công Ty Luật TNHH Luật Sư Nam cung cấp dịch vụ tư vấn pháp lý và hỗ trợ chuẩn bị hồ sơ. Hoạt động công chứng, lời chứng và quyết định tiếp nhận hồ sơ thuộc thẩm quyền của công chứng viên, tổ chức hành nghề công chứng.",
        "steps_title": "Quy trình hỗ trợ",
        "steps": [
            ("Xác định giao dịch", "Làm rõ chủ thể, tài sản, mục đích và thời gian dự kiến."),
            ("Kiểm tra điều kiện", "Rà soát giấy tờ, quyền định đoạt và hạn chế pháp lý."),
            ("Hoàn thiện văn bản", "Đề xuất điều khoản và chuẩn hóa hồ sơ cần nộp."),
            ("Phối hợp công chứng", "Hỗ trợ đặt lịch và bổ sung theo yêu cầu hợp lệ."),
            ("Hướng dẫn sau ký", "Lưu hồ sơ, thanh toán, đăng ký và nghĩa vụ tiếp theo."),
        ],
        "note_title": "Lưu ý",
        "note_text": "Danh mục giấy tờ và việc tiếp nhận phụ thuộc từng giao dịch, tình trạng tài sản và yêu cầu của tổ chức hành nghề công chứng có thẩm quyền.",
        "laws": ["Luật Công chứng 2024", "Bộ luật Dân sự 2015", "Luật Đất đai 2024"],
        "cta_eyebrow": "Kiểm tra trước khi ký",
        "cta_title": "Hồ sơ đầy đủ giúp buổi công chứng diễn ra thuận lợi hơn.",
        "cta_text": "Gửi loại giao dịch và giấy tờ hiện có để nhận danh mục cần chuẩn bị.",
        "related": ["thua-ke", "dat-dai-bat-dong-san", "hon-nhan-gia-dinh"],
    },
]
SERVICE_BY_SLUG = {s["slug"]: s for s in SERVICES}

# ---------------------------------------------------------------------------
# Bài viết pháp lý. Nội dung từng bài: src/bai-viet/<slug>.html
# ---------------------------------------------------------------------------
ARTICLES = [
    {
        "slug": "thoi-hieu-chia-di-san-thua-ke",
        "title": "Thời hiệu chia di sản thừa kế: mốc 30 năm, 10 năm và 03 năm theo Bộ luật Dân sự 2015",
        "card_title": "Thời hiệu chia di sản thừa kế: mốc 30 năm, 10 năm và 03 năm",
        "seo_title": "Thời hiệu chia di sản thừa kế theo Bộ luật Dân sự 2015",
        "description": "Thời hiệu yêu cầu chia di sản là 30 năm với bất động sản, 10 năm với động sản. Phân tích Điều 623 Bộ luật Dân sự 2015, hệ quả khi hết thời hiệu và việc cần làm sớm.",
        "excerpt": "Mốc tính thời hiệu, ba loại thời hiệu tại Điều 623 Bộ luật Dân sự 2015 và điều gì xảy ra với di sản khi hết thời hạn.",
        "service": "thua-ke",
        "category": "Thừa kế",
        "published": "2026-09-15",
        "modified": "2026-09-24",
        "image_alt": "Luật sư ký văn bản thỏa thuận phân chia di sản",
        "related_services": ["thua-ke", "cong-chung", "tranh-tung-giai-quyet-tranh-chap"],
    },
    {
        "slug": "ly-hon-don-phuong",
        "title": "Ly hôn đơn phương: căn cứ, hồ sơ và cách Tòa án xem xét quyền nuôi con",
        "card_title": "Ly hôn đơn phương: căn cứ, hồ sơ và quyền nuôi con",
        "seo_title": "Ly hôn đơn phương: căn cứ, hồ sơ, quyền nuôi con",
        "description": "Khi nào Tòa án giải quyết ly hôn theo yêu cầu của một bên, hồ sơ cần chuẩn bị, Tòa án có thẩm quyền và nguyên tắc giao con, cấp dưỡng, chia tài sản chung.",
        "excerpt": "Căn cứ ly hôn theo Điều 56 Luật Hôn nhân và Gia đình 2014, hồ sơ khởi kiện, quyền nuôi con và chia tài sản chung.",
        "service": "hon-nhan-gia-dinh",
        "category": "Hôn nhân & Gia đình",
        "published": "2026-09-10",
        "modified": "2026-09-24",
        "image_alt": "Búa phán quyết trên bàn xét xử của Tòa án",
        "related_services": ["hon-nhan-gia-dinh", "tranh-tung-giai-quyet-tranh-chap", "cong-chung"],
    },
    {
        "slug": "dat-coc-mua-ban-nha-dat",
        "title": "Đặt cọc mua bán nhà đất: 6 điểm cần kiểm tra trước khi xuống tiền",
        "card_title": "Đặt cọc mua bán nhà đất: 6 điểm cần kiểm tra trước khi xuống tiền",
        "seo_title": "Đặt cọc mua bán nhà đất: 6 điểm cần kiểm tra",
        "description": "Hậu quả của đặt cọc theo Điều 328 Bộ luật Dân sự 2015 và 6 điểm cần kiểm tra trước khi đặt cọc mua nhà đất: chủ thể, điều kiện chuyển nhượng, quy hoạch.",
        "excerpt": "Phạt cọc hoạt động thế nào, điều kiện chuyển nhượng theo Luật Đất đai 2024 và những điều khoản nên có trong hợp đồng đặt cọc.",
        "service": "dat-dai-bat-dong-san",
        "category": "Đất đai & Bất động sản",
        "published": "2026-09-05",
        "modified": "2026-09-24",
        "image_alt": "Khu cao ốc và nhà ở tại đô thị",
        "related_services": ["dat-dai-bat-dong-san", "cong-chung", "dan-su"],
    },
]
ARTICLE_BY_SLUG = {a["slug"]: a for a in ARTICLES}


def articles_for_service(slug):
    return [a for a in ARTICLES if slug in a["related_services"]]


# ---------------------------------------------------------------------------
# Câu hỏi thường gặp (chuyển từ trang Liên hệ của website cũ)
# ---------------------------------------------------------------------------
FAQ = [
    {
        "id": "chi-phi-thue-luat-su",
        "q": "Chi phí thuê luật sư được tính như thế nào?",
        "a": [
            "Thù lao luật sư được hai bên thỏa thuận trước và ghi trong hợp đồng dịch vụ pháp lý. Theo <strong>Điều 55 Luật Luật sư</strong>, căn cứ tính thù lao gồm nội dung và tính chất của dịch vụ, thời gian và công sức của luật sư, cùng kinh nghiệm và uy tín của luật sư.",
            "Cũng theo điều luật này, thù lao có thể tính theo <strong>giờ làm việc</strong>, theo <strong>vụ việc với mức trọn gói</strong>, theo <strong>tỷ lệ phần trăm</strong> giá ngạch vụ kiện hoặc giá trị hợp đồng, hoặc theo <strong>hợp đồng dài hạn</strong> với mức cố định. Chúng tôi đề xuất phương thức phù hợp với tính chất vụ việc và thông báo trước mọi khoản phát sinh. Xem thêm <a href=\"{{root}}vi-sao-chon-chung-toi/\">cam kết minh bạch về chi phí</a>.",
        ],
    },
    {
        "id": "cam-ket-thang-kien",
        "q": "Luật sư có cam kết chắc chắn thắng kiện không?",
        "a": [
            "Không. Chúng tôi phân tích thẳng thắn điểm mạnh, điểm yếu trong hồ sơ và khả năng thành công dựa trên chứng cứ cùng quy định pháp luật, nhưng không đưa ra cam kết bảo đảm kết quả.",
            "Bộ Quy tắc Đạo đức và Ứng xử nghề nghiệp luật sư Việt Nam nghiêm cấm luật sư hứa hẹn, cam kết bảo đảm kết quả vụ việc về những nội dung nằm ngoài khả năng và điều kiện thực hiện của luật sư (<strong>Quy tắc 9.1.6</strong>). Nếu một đơn vị cam kết chắc chắn thắng kiện, đó là dấu hiệu bạn nên cân nhắc rất kỹ.",
        ],
    },
    {
        "id": "bao-mat-thong-tin",
        "q": "Thông tin tôi cung cấp có được giữ bí mật không?",
        "a": [
            "Có. Luật sư không được tiết lộ thông tin về vụ việc, về khách hàng mà mình biết được trong khi hành nghề, trừ trường hợp được khách hàng đồng ý bằng văn bản hoặc pháp luật có quy định khác, theo <strong>Điều 25 Luật Luật sư</strong> và <strong>Quy tắc 7</strong> Bộ Quy tắc Đạo đức và Ứng xử nghề nghiệp luật sư Việt Nam.",
            "Nghĩa vụ bảo mật áp dụng ngay từ buổi trao đổi đầu tiên, kể cả khi sau đó hai bên không ký hợp đồng dịch vụ, và vẫn tiếp tục có hiệu lực sau khi vụ việc kết thúc.",
        ],
    },
    {
        "id": "chuan-bi-buoi-dau",
        "q": "Buổi trao đổi đầu tiên tôi cần chuẩn bị những gì?",
        "a": [
            "Bạn nên mang theo bản sao các tài liệu đang có: hợp đồng, giấy tờ về tài sản, thông báo hoặc quyết định đã nhận từ cơ quan nhà nước, tin nhắn và email trao đổi giữa các bên.",
            "Quan trọng không kém là một bản tóm tắt diễn biến theo trình tự thời gian và câu trả lời cho câu hỏi: bạn mong muốn đạt được điều gì. Danh mục chi tiết có tại trang <a href=\"{{root}}quy-trinh-lam-viec/\">Quy trình làm việc</a> và trang của từng <a href=\"{{root}}dich-vu/\">lĩnh vực dịch vụ</a>.",
        ],
    },
    {
        "id": "thoi-han-quan-trong",
        "q": "Vì sao thời hạn lại quan trọng đến vậy?",
        "a": [
            "Pháp luật quy định thời hiệu khởi kiện và thời hạn thực hiện quyền cho từng loại vụ việc. Khi thời hiệu đã hết và có đương sự yêu cầu áp dụng, quyền khởi kiện có thể không còn được bảo vệ, dù nội dung yêu cầu của bạn là có căn cứ. Ví dụ điển hình là <a href=\"{{root}}kien-thuc-phap-ly/thoi-hieu-chia-di-san-thua-ke/\">thời hiệu chia di sản thừa kế</a>.",
            "Tương tự, thời hạn kháng cáo bản án, thời hạn khiếu nại quyết định hành chính đều rất ngắn. Vì vậy bạn nên liên hệ luật sư <strong>càng sớm càng tốt</strong>, ngay khi nhận được văn bản đầu tiên.",
        ],
    },
    {
        "id": "vu-viec-ngoai-tphcm",
        "q": "Công ty có nhận vụ việc ngoài Thành phố Hồ Chí Minh không?",
        "a": [
            "Có. Luật sư Việt Nam được hành nghề trên phạm vi toàn quốc, nên chúng tôi nhận tư vấn và tham gia tố tụng tại các tỉnh, thành phố khác.",
            "Với vụ việc ở xa, phần lớn công đoạn tư vấn và chuẩn bị hồ sơ có thể thực hiện trực tuyến; chi phí đi lại (nếu có) được thông báo và thống nhất trước khi phát sinh.",
        ],
    },
    {
        "id": "thoi-gian-phan-hoi",
        "q": "Gửi yêu cầu qua website thì bao lâu được phản hồi?",
        "a": [
            "Chúng tôi phản hồi trong giờ làm việc, thường trong vòng 24 giờ làm việc kể từ khi nhận được yêu cầu. Với vụ việc khẩn cấp, đặc biệt là <a href=\"{{root}}dich-vu/hinh-su/\">vụ án hình sự</a> hoặc sắp hết thời hạn kháng cáo, bạn nên gọi trực tiếp hotline <a href=\"tel:0983498499\">0983 498 499</a>.",
            "Lưu ý: việc gửi yêu cầu qua website chưa làm phát sinh quan hệ luật sư – khách hàng. Quan hệ này chỉ hình thành khi hai bên ký kết hợp đồng dịch vụ pháp lý.",
        ],
    },
]
